steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'us-central1-docker.pkg.dev/img-studio-terraform-deploy/img-studio-repo/imgstudio:latest',
        '--build-arg',
        '_NEXT_PUBLIC_PROJECT_ID=img-studio-terraform-deploy',
        '--build-arg',
        '_NEXT_PUBLIC_VERTEX_API_LOCATION=us-central1',
        '--build-arg',
        '_NEXT_PUBLIC_GCS_BUCKET_LOCATION=us-central1',
        '--build-arg',
        '_NEXT_PUBLIC_GEMINI_MODEL=gemini-2.0-flash-001',
        '--build-arg',
        '_NEXT_PUBLIC_SEG_MODEL=gemini-2.0-flash-001',
        '--build-arg',
        '_NEXT_PUBLIC_EDIT_ENABLED=true',
        '--build-arg',
        '_NEXT_PUBLIC_VEO_ENABLED=true',
        '--build-arg',
        '_NEXT_PUBLIC_VEO_ITV_ENABLED=true',
        '--build-arg',
        '_NEXT_PUBLIC_VEO_ADVANCED_ENABLED=true',
        '--build-arg',
        '_NEXT_PUBLIC_PRINCIPAL_TO_USER_FILTERS=',
        '--build-arg',
        '_NEXT_PUBLIC_OUTPUT_BUCKET=img-studio-terraform-deploy-imgstudio-output',
        '--build-arg',
        '_NEXT_PUBLIC_TEAM_BUCKET=img-studio-terraform-deploy-imgstudio-library',
        '--build-arg',
        '_NEXT_PUBLIC_EXPORT_FIELDS_OPTIONS_URI=gs://img-studio-terraform-deploy-imgstudio-export-cfg/export-fields-options.json',
        '--build-arg',
        '_NEXT_PUBLIC_FIREBASE_API_KEY=AIzaSyCJBwmhK_TWsAw3-KK2jDq1JK6gTYOvTUE',
        '--build-arg',
        '_NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=img-studio-terraform-deploy.firebaseapp.com',
        '--build-arg',
        '_NEXT_PUBLIC_FIREBASE_PROJECT_ID=img-studio-terraform-deploy',
        '--build-arg',
        '_NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=img-studio-terraform-deploy.appspot.com',
        '--build-arg',
        '_NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=',
        '--build-arg',
        '_NEXT_PUBLIC_FIREBASE_APP_ID=',
        '.',
      ]

    # script: |
    #   docker build -t us-central1-docker.pkg.dev/img-studio-terraform-deploy/img-studio-repo/imgstudio:latest .
    # automapSubstitutions: true
images:
- 'us-central1-docker.pkg.dev/img-studio-terraform-deploy/img-studio-repo/imgstudio:latest'
